In [1]:
# UNINASSAU - 2MC ESTRUTURA DE DADOS
# DOCENTE: PROF. MSC. CLOVES
# ESTUDANTE: ...

IMC = [181, #ALTURA
       100, #PESO
        40] #IDADE
print(IMC)

[181, 100, 40]


In [2]:
NOTAS = [ 10, #N1
           9, #N2
           8, #N3
           7] #N4
print(NOTAS)

[10, 9, 8, 7]


In [ ]:
def vet_add(vet1, vet2):
  # soma elementos correspondentes
return [vet1_i + vet2_i
        for vet1_i, vet2_i in zip(vet1, vet2)]


In [ ]:
fila = [100, 101, 102, 103, 104]
fila.append(105) #insere um elemento no final
print(fila)

In [ ]:
def vet_sub(vet1, vet2):
  # subtrai elementos correspondentes
return [vet1_i - vet2_i
        for vet1_i, vet2_i in zip(vet1, vet2)]


In [ ]:
import numpy as np
matriz = np.array([[0,1,2], [3,4,5], [6,7,8]])
elemnto = matriz[0,1] #Obtém o elemento

num_linhas = matriz.shape[0]
num_colunas = matriz.shape[1]

for linha in matriz:
  for elemento in linha:
    print(elemento)

In [ ]:
# Operações matricias
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6 ], [7, 8]])

soma = matriz1 + matriz2
produto = np.dot(matriz1, matriz2)
print(soma)
print(produto)

In [9]:
# Transposição de matriz
m_transposta = matriz.T
a = 2
b = 3
a = b
print(a)

3


In [10]:
# Indexação booleana
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
condicao = matriz > 5 # Cria uma matriz de booleanos
elemento_maiores_q_5 = matriz[condicao]

In [11]:
# Outras operações úteis
media = np.mean(matriz)
valor_minimo = np.min(matriz)
valor_max = np.max(matriz)
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
